apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-demo-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/freewings463/cicd_sandbox.git
    targetRevision: main  # 示例：main / v1.2.3 / 7f3a2c1
    path: charts/app-demo
    helm:
      valueFiles:
        - envs/dev/values-dev.yaml  # 示例：envs/dev/values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: apps-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
